---
- name: Deploy PetClinic Artifact
  hosts: webserver
  remote_user: vagrant
  become: true

  tasks:
    - name: Copy artifact
      become: true
      copy:
        src: "/var/lib/jenkins/workspace/petclinic/target/spring-petclinic-3.1.0-SNAPSHOT.jar"
        dest: "/home/vagrant/spring-petclinic-3.1.0-SNAPSHOT.jar"
        owner: vagrant
        group: vagrant
        mode: 0644